name: Schedule Task Runner

on:
  workflow_dispatch:  # 允许手动触发
  schedule:  # 每日 UTC 时间 00:00 验证配置有效性
    - cron: '0 0 * * *'

env:
  PYTHON_VERSION: '3.9.12'
  CITY: '济南'  # 从 Secrets 读取更安全 (建议替换为 ${{ secrets.CITY }})
  TZ: 'Asia/Shanghai'  # 设置时区

jobs:
  setup-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 单次验证超时时间

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'  # 启用 pip 缓存

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libffi-dev

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt \
          --no-cache-dir \
          -i https://pypi.tuna.tsinghua.edu.cn/simple

    - name: Validate task execution
      run: |
        # 单次验证模式，检查关键功能是否正常
        python -c "from main import get_access_token; print('AccessToken:', get_access_token())"
        python -c "from main import weather_report; weather_report('${{ env.CITY }}')"
      env:
        API_SECRET: ${{ secrets.API_SECRET }}  # 从仓库 Secrets 读取敏感信息
