name: weixin
on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间23点0分，北京时间需要+8小时，代表北京时间上午7点运行
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libffi-dev

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt \
            --no-cache-dir \
            --progress-bar off \
            -i https://pypi.tuna.tsinghua.edu.cn/simple

      - name: weixin
        run: python3 main.py
