name: weixin
on:
  workflow_dispatch:
  schedule:
    # 国际标准时间 23 点（北京时间次日上午 7 点）
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.12

      - name: Set timezone
        run: sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run weixin script
        run: python3 main.py
